server {
    listen 80;
    
    location / {
        # Route all root web requests directly to the internal Kubernetes Backend Service
        proxy_pass http://backend-api-svc:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}